package one.realme.wallet

/**
 * Address receive and send coin
 *
 * Generated by private key
 */
class Address {
    companion object {
        /**
         * create new wallet
         */
        fun create(): Address {
            return Address()
        }
    }
}